version: 2
jobs:
  build:
    docker:
      - image: uobikiemukot/archlinux-circleci:latest
    steps:
      - checkout
      - run:
          name: build yaft
          command: make
      - run:
          name: build yaftx
          command: make yaftx
