main :: IO ()
main = do
	line <- getLine
	if null line
		then return ()
		else do
			putStrLn line
			main

rom2hira :: String -> Char
rom2hira (x:xs)
	| x == 'a' = 'あ'
	| x == 'i' = 'い'
	| x == 'u' = 'う'
	| x == 'e' = 'え'
	| x == 'o' = 'お'
	| xx == "ca" = 'か'
	| xx == "ci" = 'き'
	| xx == "cu" = 'く'
	| xx == "ce" = 'け'
	| xx == "co" = 'こ'
	| xx == "sa" = 'さ'
	| xx == "si" = 'し'
	| xx == "su" = 'す'
	| xx == "se" = 'せ'
	| xx == "so" = 'そ'
	| xx == "ta" = 'た'
	| xx == "ti" = 'ち'
	| xx == "tu" = 'つ'
	| xx == "te" = 'て'
	| xx == "to" = 'と'
	| xx == "na" = 'な'
	| xx == "ni" = 'に'
	| xx == "nu" = 'ぬ'
	| xx == "ne" = 'ね'
	| xx == "no" = 'の'
	| xx == "ha" = 'は'
	| xx == "hi" = 'ひ'
	| xx == "hu" = 'ふ'
	| xx == "he" = 'へ'
	| xx == "ho" = 'ほ'
	| xx == "ma" = 'ま'
	| xx == "mi" = 'み'
	| xx == "mu" = 'む'
	| xx == "me" = 'め'
	| xx == "mo" = 'も'
	| xx == "ya" = 'や'
	| xx == "yu" = 'ゆ'
	| xx == "yo" = 'よ'
	| xx == "ra" = 'ら'
	| xx == "ri" = 'り'
	| xx == "ru" = 'る'
	| xx == "re" = 'れ'
	| xx == "ro" = 'ろ'
	| xx == "wa" = 'わ'
	| xx == "wo" = 'を'
	| xx == "nn" = 'ん'
	| xx == "n" = 'ん'
	| xx == "ga" = 'が'
	| xx == "gi" = 'ぎ'
	| xx == "gu" = 'ぐ'
	| xx == "ge" = 'げ'
	| xx == "go" = 'ご'
	| xx == "za" = 'ざ'
	| xx == "zi" = 'じ'
	| xx == "zu" = 'ず'
	| xx == "ze" = 'ぜ'
	| xx == "zo" = 'ぞ'
	| xx == "da" = 'だ'
	| xx == "di" = 'ぢ'
	| xx == "du" = 'づ'
	| xx == "de" = 'で'
	| xx == "do" = 'ど'
	| xx == "ba" = 'ば'
	| xx == "bi" = 'び'
	| xx == "bu" = 'ぶ'
	| xx == "be" = 'べ'
	| xx == "bo" = 'ぼ'
	| xx == "pa" = 'ぱ'
	| xx == "pi" = 'ぴ'
	| xx == "pu" = 'ぷ'
	| xx == "pe" = 'ぺ'
	| xx == "po" = 'ぽ'
	where
		xx = take 2 (x:xs)
